### PR TITLE
use pip3 to install gigalixir CLI

### LINKED ISSUE #21: pip install gigalixir failing
Hi, I'm getting the following error today when trying to deploy

```bash

Installing gigalixir
  /usr/bin/sudo pip install gigalixir --ignore-installed six
  The directory '/home/runner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  The directory '/home/runner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting gigalixir
    Downloading https://files.pythonhosted.org/packages/66/98/c698c1577d1f3aec71a71df51af39547aace3a79f3e5c724ab203cd9a542/gigalixir-1.2.2.tar.gz
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-QkIpa5/gigalixir/setup.py", line 41, in <module>
          'sure',
        File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
          replace_conflicting=True,
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
          replace_conflicting=replace_conflicting
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
          return installer(requirement)
        File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
          return cmd.easy_install(req)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1165, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QkIpa5/gigalixir/
Error: The process '/usr/bin/sudo' failed with exit code 1
```

This is from yesterday's logs (when I deployed successfully
```bash

Installing gigalixir
  /usr/bin/sudo pip install gigalixir --ignore-installed six
  The directory '/home/runner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  The directory '/home/runner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting gigalixir
    Downloading https://files.pythonhosted.org/packages/66/98/c698c1577d1f3aec71a71df51af39547aace3a79f3e5c724ab203cd9a542/gigalixir-1.2.2.tar.gz
  Collecting six
    Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
  Collecting click>=6.7 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
  Collecting pyOpenSSL>=19.1.0 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/b2/5e/06351ede29fd4899782ad335c2e02f1f862a887c20a3541f17c3fa1a3525/pyOpenSSL-20.0.1-py2.py3-none-any.whl (54kB)
  Collecting pygments>=2.2.0 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl (896kB)
  Collecting qrcode>=6.1 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/42/87/4a3a77e59ab7493d64da1f69bf1c2e899a4cf81e51b2baa855e8cc8115be/qrcode-6.1-py2.py3-none-any.whl
  Collecting requests>=2.20.0 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
  Collecting rollbar>=0.13.11 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/9d/b1/7c51f2308bdea13c857aab16ef0bdb786231401d7236575db1c60de50282/rollbar-0.15.2.tar.gz (49kB)
  Collecting stripe>=1.28.0 (from gigalixir)
    Downloading https://files.pythonhosted.org/packages/81/b0/f849388f242bc1ffb1570c5fe5173f7d7ab308a3131ff7926da8c5c058e8/stripe-2.55.2-py2.py3-none-any.whl (204kB)
  Collecting cryptography>=3.2 (from pyOpenSSL>=19.1.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/86/41/44173175d378c9e3a73294bb33c73725f7726def5ce267af6bd11b72eb23/cryptography-3.3.2-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
  Collecting chardet<5,>=3.0.2 (from requests>=2.20.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
  Collecting certifi>=2017.4.17 (from requests>=2.20.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
  Collecting urllib3<1.27,>=1.21.1 (from requests>=2.20.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137kB)
  Collecting idna<3,>=2.5 (from requests>=2.20.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
  Collecting enum34; python_version < "3" (from cryptography>=3.2->pyOpenSSL>=19.1.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
  Collecting cffi>=1.12 (from cryptography>=3.2->pyOpenSSL>=19.1.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/50/5e/b4d3cff96422425dfcaa0a09414b5b17b311e74e56a4c457b16396dd73a7/cffi-1.14.4-cp27-cp27mu-manylinux1_x86_64.whl (389kB)
  Collecting ipaddress; python_version < "3" (from cryptography>=3.2->pyOpenSSL>=19.1.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
  Collecting pycparser (from cffi>=1.12->cryptography>=3.2->pyOpenSSL>=19.1.0->gigalixir)
    Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
  Installing collected packages: click, six, enum34, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, pygments, qrcode, chardet, certifi, urllib3, idna, requests, rollbar, stripe, gigalixir
    Running setup.py install for rollbar: started
      Running setup.py install for rollbar: finished with status 'done'
    Running setup.py install for gigalixir: started
      Running setup.py install for gigalixir: finished with status 'done'
  Successfully installed certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 click-7.1.2 cryptography-3.3.2 enum34-1.1.10 gigalixir-1.2.2 idna-2.10 ipaddress-1.0.23 pyOpenSSL-20.0.1 pycparser-2.20 pygments-2.5.2 qrcode-6.1 requests-2.25.1 rollbar-0.15.2 six-1.15.0 stripe-2.55.2 urllib3-1.26.3
```

Not sure what the problem is yet- the `.tar.gz` path looks the same in both cases. Could something changed with the underlying Github infra?

### PR DESCRIPTION
**Pull request by vlindhol**
Python 2 [reached EOL](https://gigalixir.readthedocs.io/en/latest/getting-started-guide.html#prerequisites) at January 1st 2020, should hopefully fix #21 but I don't know Github Actions well enough to test it :D

### CODE REVIEW

**Review by mhanberg — CHANGES_REQUESTED** [review]
Please 
- Update the change log
- Commit the built js file
- Test out this branch yourself to see if it works

**Comment by Sgoettschkes** [comment]
I tried the change and the error persists.

@vlindhol You can try the changes you do in your branch by using it in a workflow like this:

```
- uses: vlindhol/gigalixir-action@use-python3
```

instead of the usual `mhanberg/gigalixir-action@v0.4.0`. This way you can try your changes and if it works, you can create a PR.

**Comment by erikcameron** [comment]
Hey all, this also did not work for me, but de-sudoing the call to pip did. See PR #23 , let me know if there's anything else I can help with.

**Comment by mhanberg** [comment]
Fixed in #23, thanks for the effort! I appreciate it.

**Pull request closed without merging**
