### PR TITLE
Only runs migrations if input is "true"

### PR DESCRIPTION
**Pull request by bahelms**
Also fixes uncaught error in promise.

### CODE REVIEW

**Comment by mhanberg** [comment]
@bahelms Please test on master and then I can tag the release.

Thanks again!

**Comment by bahelms** [comment]
Works like a charm on master!

**Comment by mhanberg** [comment]
I released v0.2.1 with this functionality, thanks for the contribution!

**Comment by bahelms** [comment]
Thanks for doing all the work!

**Pull request merged**
